### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by frolic** [latticexyz/opcraft#9]
Didn't want to spam you with issues but wanted to keep track of rough edges as I find them:
- [ ] move to pnpm for monorepo/package management (faster, less error prone)
- [ ] move local dev to single script, using pnpm recursive option or something like [overmind](https://github.com/DarthSim/overmind)
- [x] gravity/physics feels weird, player should feel heavier
- [x] client should recalculate position/physics on block updates (maybe just in same chunk), otherwise you're left floating if a block under you is mined
- [ ] scrolling should rotate selected item
- [ ] regaining focus in game engine after being outside (esc) shouldn't immediately interact with the world (clicking back into the game will e.g. immediately mine a block)
  (not as big an issue now that there's a block break animation)
- [x] should only be able to jump from a block, not from air (currently can fly by spamming jump)
- [ ] no way to toggle off sound once toggled on
- [x] holding down mouse while breaking a block should start breaking the next block under cursor
- [ ] hovering over a block should highlight the whole thing rather than one face?
- [ ] mining grass should give a dirt block?
- [ ] consider moving to [debug](https://www.npmjs.com/package/debug) for console logs so they can be namespaced and filtered
- [ ] need ways to toggle developer tools (query UI, sound, coords, etc)
- [ ] leaves on ground show under the world rather than the next block down
